[metadata]
name=virtualgps
version=2.0.0
url=https://github.com/rkaczorek/virtualgps
description=Pseudo terminal GPS simulator
long_description=file:README.md
author=Radek Kaczorek
author_email=rkaczorek@gmail.com
license=GPL-3
classifiers=
   License :: OSI Approved :: License :: OSI Approved :: GNU General Public License v3 (GPLv3)
   Natural Language :: English
   Programming Language :: Python
   Operating System :: OS Independent
   Intended Audience :: Science/Research
   Topic :: Scientific/Engineering :: GIS

[options]
packages = virtualgps
python_requires=>=3.8,<4
install_requires=
   configparser >= 7.1.0
   requests >= 2.32.3
   DateTime >= 5.5

[options.entry_points]
console_scripts =
   virtual-gps = virtualgps.main:main